// <auto-generated />
using System;
using BookStoreApi.AppContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStoreApi.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260726181153_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bookapi")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookStoreApi.Models.BookModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalPages")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books", "bookapi");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f2d4a91-7c35-4b6e-9d12-1a3f5e7c9b20"),
                            Author = "Paulo Coelho",
                            Category = "Fiction",
                            Description = "The Alchemist follows the journey of an Andalusian shepherd",
                            Language = "English",
                            Title = "The Alchemist",
                            TotalPages = 208
                        },
                        new
                        {
                            Id = new Guid("3c7e9b12-5a48-4d90-a621-2f8b6c4e0d73"),
                            Author = "Harper Lee",
                            Category = "Fiction",
                            Description = "A novel about the serious issues of rape and racial inequality.",
                            Language = "English",
                            Title = "To Kill a Mockingbird",
                            TotalPages = 281
                        },
                        new
                        {
                            Id = new Guid("6a1f4e83-9d25-4b70-b638-5c2e8a7f1d94"),
                            Author = "George Orwell",
                            Category = "Fiction",
                            Description = "A dystopian social science fiction novel and cautionary tale about the dangers of totalitarianism. ",
                            Language = "English",
                            Title = "1984",
                            TotalPages = 328
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
